# Generated by Django 4.2.7 on 2023-11-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PogonageUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=40)),
                ('metal_thickness', models.IntegerField()),
                ('unit_length', models.IntegerField()),
                ('unit_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('unit_cost', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SheetUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=40)),
                ('metal_thickness', models.IntegerField()),
                ('unit_width', models.IntegerField()),
                ('unit_height', models.IntegerField()),
                ('unit_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('unit_cost', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sortament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length_pogon', models.IntegerField()),
                ('width_sheet', models.IntegerField()),
                ('height_sheet', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.product')),
            ],
        ),
        migrations.CreateModel(
            name='SortamentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sortament_id', models.ManyToManyField(to='calculation.sortament')),
                ('unit_pogonage_id', models.ManyToManyField(to='calculation.pogonageunit')),
                ('unit_sheet_id', models.ManyToManyField(to='calculation.sheetunit')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='./media/photos')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.product')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='./media/files')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.product')),
            ],
        ),
    ]
